### ISSUE TITLE
Bitbucket support.

### ISSUE THREAD

**Issue by VolodymyrPliuta** [md-command-line/gh_reveal#37]
7999/on/repo-name

origin	ssh://git@git.organization.com:7999/org-name/repo-name.git

https://git.organization.com/projects/org-name/repos/repo-name/browse

also works: 
https://git.organization.com/projects/org-name/repos/repo-name

**Comment by MichaelDimmitt** [comment]
this is currently working.

**Comment by MichaelDimmitt** [comment]
please reopen or comment if not the case.
but it works for the bitbucket accounts that I use.
